import React from 'react';

export const studyPlanData = {
    "Week 1": [
        {
            day: 1,
            theme: "Unveiling the Challenge & Strategy Foundation",
            goal: "Understand your baseline, the PTE structure, and how to use the platform.",
            sessions: [
                {
                    title: "Morning Focus",
                    time: "90 mins",
                    activities: [
                        { description: "Take the full Interactive Diagnostic Test.", tool: "Interactive Diagnostic Test" },
                        { description: "Analyze your Diagnostic Report & watch introductory videos.", tool: "Performance Analytics Dashboard", materials: {
                            title: "Diagnostic Report Interpretation",
                            content: React.createElement('div', { className: 'prose' },
                                React.createElement('p', null, "Your diagnostic report gives you a baseline for your studies. Here's how to read it:"),
                                React.createElement('ul', null,
                                    React.createElement('li', null, React.createElement('strong', null, "Communicative Skills (Listening, Reading, Speaking, Writing):"), " These are your main scores. A score below 65 suggests a need for significant focus."),
                                    React.createElement('li', null, React.createElement('strong', null, "Enabling Skills (e.g., Pronunciation, Vocabulary):"), " These scores tell you WHY your main scores are what they are. A low Pronunciation score will directly impact your Speaking score.")
                                )
                            )
                        }},
                    ]
                },
                {
                    title: "Evening Review",
                    time: "60 mins",
                    activities: [
                        { description: "Set up your Adaptive Vocabulary Builder.", tool: "Adaptive Vocabulary Builder", materials: {
                            title: "Your First Vocabulary Set",
                            content: React.createElement('ul', { className: 'list-disc pl-5' }, 
                                ['constitute', 'derive', 'evident', 'assess', 'indicate', 'legislate', 'principle', 'proceed', 'require', 'structure'].map(word => React.createElement('li', { key: word }, word))
                            )
                        }},
                    ]
                }
            ]
        },
        {
            day: 2,
            theme: "Mastering Read Aloud (RA)",
            goal: "Improve pronunciation and fluency for Read Aloud.",
            sessions: [
                {
                    title: "Morning Focus",
                    time: "90 mins",
                    activities: [
                        { description: "Practice 10 untimed Read Aloud questions.", navigateToView: 'read-aloud', materials: {
                            title: "Read Aloud Practice Passages",
                            content: React.createElement('div', { className: 'prose' },
                                React.createElement('p', null, "The proliferation of digital media has fundamentally altered traditional paradigms of information dissemination. Whereas previously, established institutions acted as gatekeepers of content, the internet facilitates a decentralized model where individuals can both consume and create information, leading to a more democratized but also more fragmented public sphere."),
                                React.createElement('hr', null),
                                React.createElement('p', null, "Marine biology is the scientific study of organisms in the ocean or other marine bodies of water. Given that in biology many phyla, families and genera have some species that live in the sea and others that live on land, marine biology classifies species based on the environment rather than on taxonomy.")
                            )
                        }},
                    ]
                },
                {
                    title: "Afternoon Reinforcement",
                    time: "90 mins",
                    activities: [
                        { description: "Complete 15 timed RA questions and submit to the AI evaluator.", navigateToView: 'read-aloud' }
                    ]
                },
                {
                    title: "Evening Review",
                    time: "60 mins",
                    activities: [
                        { description: "Use the Pronunciation Practice Lab for flagged sounds.", tool: "Pronunciation Practice Lab" },
                        { description: "Continue with the Adaptive Vocabulary Builder.", tool: "Adaptive Vocabulary Builder" }
                    ]
                }
            ]
        },
        { day: 3, theme: "Conquering Repeat Sentence (RS)", goal: "Improve short-term memory and fluency for RS.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 15 Repeat Sentence questions.", navigateToView: 'repeat-sentence' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 25 timed RS questions and submit to the AI evaluator.", navigateToView: 'repeat-sentence' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Use the Grammar & Syntax Workshop.", tool: "Grammar & Syntax Workshop" }, { description: "Continue with the Adaptive Vocabulary Builder.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 4, theme: "Dominating Describe Image (DI)", goal: "Develop a consistent, fluent template for describing any image.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 10 Describe Image questions using a template.", navigateToView: 'describe-image', materials: { title: "Describe Image Template", content: React.createElement('div', {className: 'prose'}, React.createElement('p', null, "The provided image, which is a [type of chart], gives information about [topic of chart]. Overall, the most striking feature is [main trend or key feature]. According to the graph, the highest point is [value] for [category], while the lowest is [value] for [category]. In conclusion, the image clearly shows [summarize the main point].")) } }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 15 timed DI questions and submit to AI evaluator.", navigateToView: 'describe-image' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Use the Pronunciation Practice Lab for numbers and trends.", tool: "Pronunciation Practice Lab" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 5, theme: "Tackling Re-tell Lecture (RL) & Answer Short Question (ASQ)", goal: "Master note-taking for RL and quick recall for ASQ.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 5 Re-tell Lecture questions, focusing on note-taking.", navigateToView: 'retell-lecture' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 5 timed RLs and 20 timed ASQs.", navigateToView: 'retell-lecture' }, { description: "", navigateToView: 'answer-short-question'}] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review lecture notes.", tool: "Digital Notebook" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 6, theme: "Integrated Speaking Practice", goal: "Build stamina and transition smoothly between speaking tasks.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Create a custom practice set: 5 RA, 8 RS, 3 DI, 2 RL, 5 ASQ.", tool: "Custom Practice Set Builder" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review week's vocabulary and prepare for the mock test.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 7, theme: "Weekly Review & Mini-Mock Test", goal: "Assess progress and identify persistent errors from Week 1.", sessions: [ { title: "Mock Test", time: "2 hours", activities: [{ description: "Take a timed Mini-Mock Test (Speaking section only).", tool: "Timed Mock Test Environment" }] }, { title: "Analysis", time: "1-2 hours", activities: [{ description: "Deeply analyze your mock test report and the Performance Analytics Dashboard.", tool: "Performance Analytics Dashboard" }] } ] }
    ],
    "Week 2": [
        { day: 8, theme: "Summarize Written Text (SWT)", goal: "Learn to identify main ideas and write a concise, grammatically correct single sentence.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice finding topic sentences in 5 passages.", navigateToView: 'summarize-written-text' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 5 timed SWT tasks and submit to AI evaluator.", navigateToView: 'summarize-written-text' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Use Grammar Workshop for complex sentences.", tool: "Grammar & Syntax Workshop" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 9, theme: "Write Essay (WE)", goal: "Master a high-scoring essay template and time management.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Memorize a 4-paragraph essay template.", navigateToView: 'write-essay', materials: { title: "High-Scoring Essay Template", content: React.createElement('div', {className: 'prose'}, React.createElement('h4', null, 'Introduction (approx. 50 words)'), React.createElement('p', null, "Paraphrase the prompt. State your clear position. Provide a brief outline of your two points."), React.createElement('h4', null, 'Body Paragraph 1 (approx. 90 words)'), React.createElement('p', null, "Start with a clear topic sentence for your first point. Explain it and provide a specific example."), React.createElement('h4', null, 'Body Paragraph 2 (approx. 90 words)'), React.createElement('p', null, "Start with a transition word (e.g., 'Furthermore'). Introduce your second point. Explain and support it."), React.createElement('h4', null, 'Conclusion (approx. 40 words)'), React.createElement('p', null, "Begin with 'In conclusion,'. Summarize your two main points and restate your position.")) } }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Write two full essays under time limit and submit to AI evaluator.", navigateToView: 'write-essay' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review essay feedback.", tool: "Performance Analytics Dashboard" }, { description: "Focus on essay vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 10, theme: "Reading - Multiple Choice", goal: "Understand skimming/scanning techniques.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 10 MCQS and 10 MCMA questions.", navigateToView: 'reading-multiple-choice-single' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 15 timed MCQS and 15 MCMA questions.", navigateToView: 'reading-multiple-choice-multiple' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review incorrect answers.", tool: "Question Bank" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 11, theme: "Reading - Re-order Paragraphs (ROP)", goal: "Learn to identify topic sentences and logical links.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 8 untimed ROP questions, noting logical connections.", navigateToView: 're-order-paragraphs' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 10 timed ROP questions.", navigateToView: 're-order-paragraphs' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Use Grammar Workshop for cohesive devices.", tool: "Grammar & Syntax Workshop" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 12, theme: "Reading - Fill in the Blanks", goal: "Improve vocabulary and collocation knowledge.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Complete 10 of each FIB type (Dropdown and Drag & Drop).", navigateToView: 'fill-in-blanks-dropdown' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 20 timed FIB questions (mixed types).", navigateToView: 'fill-in-blanks-drag-drop' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review difficult vocabulary from FIB.", tool: "Digital Notebook" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 13, theme: "Integrated Writing & Reading Practice", goal: "Combine skills and manage time across sections.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Create a custom practice set: 2 SWT, 1 WE, 5 ROP, 10 FIB (mixed).", tool: "Custom Practice Set Builder" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review week's vocabulary and prepare for full mock test.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 14, theme: "Full Mock Test 1 & Deep Dive Analysis", goal: "Experience the full test, assess stamina, and establish a new baseline score.", sessions: [ { title: "Mock Test", time: "3 hours", activities: [{ description: "Take your first Full-Length Timed Mock Test.", tool: "Timed Mock Test Environment" }] }, { title: "Analysis", time: "1-2 hours", activities: [{ description: "Analyze the detailed score report in your Performance Analytics Dashboard.", tool: "Performance Analytics Dashboard" }] } ] }
    ],
    "Week 3": [
         { day: 15, theme: "Summarize Spoken Text (SST)", goal: "Master note-taking for audio and write a concise, accurate summary.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 5 SST tasks.", navigateToView: 'summarize-spoken-text' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 5 more timed SST tasks and submit to AI evaluator.", navigateToView: 'summarize-spoken-text' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review SST notes and feedback.", tool: "Digital Notebook" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 16, theme: "Listening - Multiple Choice", goal: "Improve focus during audio and identify key information.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 10 Listening MCQS and 10 MCMA.", navigateToView: 'listening-multiple-choice-single' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Complete 15 timed Listening MCQS and 15 MCMA.", navigateToView: 'listening-multiple-choice-multiple' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review incorrect answers.", tool: "Question Bank" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 17, theme: "Listening - FIB & HCS", goal: "Enhance listening for specific words and overall meaning.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 10 Listening Fill in the Blanks.", navigateToView: 'fill-in-blanks-listening' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Practice 10 Highlight Correct Summary tasks.", navigateToView: 'highlight-correct-summary' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 18, theme: "Listening - SMW & HIW", goal: "Develop predictive listening and detailed comparison skills.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 15 Select Missing Word tasks.", navigateToView: 'select-missing-word' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Practice 15 Highlight Incorrect Words tasks.", navigateToView: 'highlight-incorrect-words' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 19, theme: "Write From Dictation (WFD)", goal: "Master short-term memory and accurate typing for this critical task.", sessions: [ { title: "Morning Focus", time: "90 mins", activities: [{ description: "Practice 25 WFDs.", navigateToView: 'write-from-dictation' }] }, { title: "Afternoon Reinforcement", time: "90 mins", activities: [{ description: "Practice another 25 WFDs, focusing on speed and accuracy.", navigateToView: 'write-from-dictation' }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review WFD sentences and errors.", tool: "Digital Notebook" }, { description: "Continue with vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 20, theme: "Integrated Listening & Weakness Workout", goal: "Combine all listening tasks and work on weak areas from Mock Test 1.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Create a custom listening-only practice test.", tool: "Custom Practice Set Builder" }, { description: "Spend one hour on your #1 weakest question type from any section.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review vocabulary.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 21, theme: "Full Mock Test 2 & Competitive Analysis", goal: "Improve on Mock Test 1 score and refine time management.", sessions: [ { title: "Mock Test", time: "3 hours", activities: [{ description: "Take your second Full-Length Timed Mock Test.", tool: "Timed Mock Test Environment" }] }, { title: "Analysis", time: "1-2 hours", activities: [{ description: "Compare Mock Test 1 and 2 side-by-side in the Performance Analytics Dashboard.", tool: "Performance Analytics Dashboard" }] } ] }
    ],
    "Week 4": [
        { day: 22, theme: "Daily Weakness Workout", goal: "Turn your weakest areas into strengths.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Target your #1 weakest question type from Mock Test 2. Do 20-25 timed examples and analyze feedback.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Final push on Vocabulary and Grammar.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 23, theme: "Daily Weakness Workout", goal: "Turn your weakest areas into strengths.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Target your #2 and #3 weakest question types. Do 15 examples of each.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review all notes.", tool: "Digital Notebook" }] } ] },
        { day: 24, theme: "Daily Weakness Workout", goal: "Turn your weakest areas into strengths.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Target your #1 weakest question type from Mock Test 2. Do 20-25 timed examples and analyze feedback.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Final push on Vocabulary and Grammar.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 25, theme: "Daily Weakness Workout", goal: "Turn your weakest areas into strengths.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Target your #2 and #3 weakest question types. Do 15 examples of each.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Review all notes.", tool: "Digital Notebook" }] } ] },
        { day: 26, theme: "Daily Weakness Workout", goal: "Turn your weakest areas into strengths.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Target your #1 weakest question type from Mock Test 2. Do 20-25 timed examples and analyze feedback.", tool: "Performance Analytics Dashboard" }] }, { title: "Evening Review", time: "60 mins", activities: [{ description: "Final push on Vocabulary and Grammar.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 27, theme: "Strategy & Mindset Masterclass", goal: "Solidify exam strategies and prepare mentally.", sessions: [ { title: "Full Session", time: "3 hours", activities: [{ description: "Review all strategy videos for high-impact tasks.", tool: "Strategy Video Library" }, { description: "Create a one-page 'Exam Day Cheat Sheet' in your Digital Notebook.", tool: "Digital Notebook", materials: { title: "Common PTE Pitfalls", content: React.createElement('ul', {className: 'list-disc pl-5'}, React.createElement('li', null, "Speaking: Forgetting to click 'Next' after you finish speaking."), React.createElement('li', null, "Writing: Is your SWT one single sentence? Is your essay word count 200-300?"), React.createElement('li', null, "Reading: Avoiding guessing on MCMA due to negative marking."), React.createElement('li', null, "Listening: Double-checking spelling on Write from Dictation.")) } }] } ] },
        { day: 28, theme: "Final Mock Test - The Dress Rehearsal", goal: "Simulate the exact exam conditions. Achieve your peak score.", sessions: [ { title: "Mock Test", time: "3 hours", activities: [{ description: "Take your final Full-Length Timed Mock Test.", tool: "Timed Mock Test Environment" }] }, { title: "Analysis", time: "1 hour", activities: [{ description: "Briefly review the report. Focus on what went right. Build confidence.", tool: "Performance Analytics Dashboard" }] } ] },
        { day: 29, theme: "Light Review & Relaxation", goal: "Consolidate knowledge without burnout.", sessions: [ { title: "Review", time: "2 hours max", activities: [{ description: "Quickly review your 'Exam Day Cheat Sheet'.", tool: "Digital Notebook" }, { description: "Do 10 WFDs and 10 RSs to stay sharp.", navigateToView: 'write-from-dictation' }, { description: "Go through your top 50 most difficult vocabulary flashcards.", tool: "Adaptive Vocabulary Builder" }] } ] },
        { day: 30, theme: "EXAM DAY", goal: "Perform at your peak.", sessions: [ { title: "Preparation", time: "N/A", activities: [{ description: "No new studying. Have a good breakfast. Trust your training. You are ready." }] } ] }
    ]
};